version: "3"
services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - "mongodb:/dat/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mongodb:
    driver: local
